baseURL = 'https://coffeeland.nibio.no/'
languageCode = 'en-us'
title = 'CoffeeLand'
theme = "ananke"
publishDir = 'public'

[params]
  description = "CoffeeLand is a collaborative initiative for sustainable coffee production and knowledge sharing."
  site_logo = "images/LOGO.png"
  background_color_class = "bg-white"
  text_color_class = "text-black"
  date_format = "2. January 2006"
  mainSections = ["news"]
  custom_css = ["css/custom.css"]

  [params.contact]
    email = 'belachew.gizachew@nibio.no'
    phone = '+47 414 80 161'

[pagination]
  pagerSize = 10

[taxonomies]
  tag = 'tags'
  category = 'categories'

[[menu.main]]
  name = 'News'
  url = '/news/'
  weight = 1

[[menu.main]]
  name = 'About'
  url = '/about/'
  weight = 2

[[menu.main]]
  name = 'Pilot Sites'
  url = '/pilot-sites/'
  weight = 3

[[menu.main]]
  name = 'Partners'
  url = '/partners/'
  weight = 4

[[menu.main]]
  name = 'Resources'
  url = '/resources/'
  weight = 5

[[menu.main]]
  name = 'Contact'
  url = '/contact/'
  weight = 6
